#!/bin/bash

CATEGORIES="dense_u64 sparse_u64 String"
DATA_STRUCTURES="ARTSet CachingARTSet HashSet BTreeSet"
BENCHES="lookup_hit lookup_miss insert_remove"

echo "data structure,data type,workload,number of elements,mean time per operation ns"
for c in $CATEGORIES; do
	for d in $DATA_STRUCTURES; do
		for b in $BENCHES; do
			for sz in $(ls "target/criterion/${d}/${c}/${b}" | grep -Ev 'report|new|base|change'); do
				avg_perf=$(cat "target/criterion/${d}/${c}/${b}/${sz}/report/index.html" |
					grep '<td>Mean</td>' -A3 |
					tail -n2 |
					head -n1 |
					cut -d'>' -f2 |
					cut -d'<' -f1 | 
					awk '{ if ($2 == "ns") { print $1 } if ($2 == "us") { print 1000 * $1 } }')
				echo "$d,$c,$b,$sz,$avg_perf"
			done
		done
	done
done
